# Generated by Django 6.0.6 on 2026-06-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designatioon',
            new_name='designation',
        ),
    ]
